=== NCIP/cagrid-grid-incubation/grid-incubation/incubator/projects/workflowManager/schema/OperationsDescriptor.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="http://tempuri.org/XMLSchema.xsd" elementFormDefault="qualified"
	xmlns="http://tempuri.org/XMLSchema.xsd" xmlns:mstns="http://tempuri.org/XMLSchema.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="Parameter">
		<xs:sequence>
			<xs:element name="name" type="xs:string" />
			<xs:element name="type" type="xs:string" />
			<xs:element name="typeNamespace" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Parameter" type="Parameter"></xs:element>

	<xs:complexType name="OperationSignature">
		<xs:sequence>
			<xs:element name="input" type="Parameter" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="output" type="OutputType" minOccurs="0" maxOccurs="1"></xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string"></xs:attribute>

	</xs:complexType>
	<xs:element name="OperationSignature" type="OperationSignature"></xs:element>
	
	
	<xs:complexType name="OutputType">
		<xs:sequence>
			<xs:element name="outputType" type="xs:string" />
			<xs:element name="outputTypeNamespace"  type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="OutputType" type="OutputType"></xs:element>
	
	
	<xs:complexType name="OperationsDescriptor">
		<xs:sequence>
			<xs:element name="service" type="ServiceDesc" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="OperationsDescriptor" type="OperationsDescriptor"></xs:element>
	
	
	<xs:complexType name="ServiceDesc">
		<xs:sequence>
			<xs:element name="serviceNamespace" type="xs:string"/>
			<xs:element name="serviceName" type="xs:string" />
			<xs:element name="serviceURL" type="xs:string" />
			<xs:element name="operations" type="Signatures"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ServiceDesc" type="ServiceDesc"></xs:element>
	
	<xs:complexType name="Signatures">
		<xs:sequence>
			<xs:element name="signature" type="OperationSignature" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Signatures" type="Signatures"></xs:element>
</xs:schema>

=== NCIP/cagrid-grid-incubation/grid-incubation/test/projects/workflowManager/resources/workflowDescriptionSamples/first.operationsDesc.xml
<?xml version="1.0" encoding="UTF-8"?>

<OperationsDescriptor  xmlns="http://tempuri.org/XMLSchema.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://tempuri.org/XMLSchema.xsd file:/C:/subversion_hawks/subversion_hawks/trunk/grid-incubation/incubator/projects/workflowManager/schema/OperationsDescriptor.xsd">
    
    <!-- First service -->
    <service>
        <serviceNamespace>http://first.cagrid.org/First</serviceNamespace>
        <serviceName>First</serviceName>
        <serviceURL>
            http://localhost:8080/wsrf/services/cagrid/First
        </serviceURL>
        <operations>
            <signature name="print">
                <output>
                    <outputType>string</outputType>
                    <outputTypeNamespace>http://www.w3.org/2001/XMLSchema</outputTypeNamespace>
                </output>
            </signature>
        </operations>
    </service>
    
    
    <!-- Second service -->
    <service>
        <serviceNamespace>http://second.cagrid.org/Second</serviceNamespace>
        <serviceName>Second</serviceName>
        <serviceURL>http://localhost:8080/wsrf/services/cagrid/Second</serviceURL>
        <operations>
            <signature name="receive">
                <input>
                    <name>input</name>
                    <type>string</type>
                    <typeNamespace>http://www.w3.org/2001/XMLSchema</typeNamespace>
                </input>
            </signature>
        </operations>
    </service>
    
</OperationsDescriptor>
